### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by JamesMilnerUK** [Geovation/tiler#27]
One of the python tests fails:
```

======================================================================
ERROR: test_create_vector_tiles (tests.test_validate_geojson.TestValidateGeojson)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tiler-scripts/tests/test_validate_geojson.py", line 12, in test_create_vector_tiles
    is_valid = validate_geojson(GEOJSON_FILE)
  File "/tiler-scripts/validate_geojson.py", line 11, in validate_geojson
    validation = geojson.is_valid(features)
AttributeError: 'module' object has no attribute 'is_valid'

```

**Comment by JamesMilnerUK** [comment]
Looks like the GeoJSON API has changed. We should probably lock down the Python library versions.
